// Multilingual SEO locale routing
export const LOCALES = [
  "es", "de", "fr", "it", "pt", "nl", "pl", "ru", "sv", "da", "no", "fi", "cs", "ro", "el", "hu", "tr", "uk", "ar", "ja", "ko", "zh", "hi"
] as const;

export type Locale = (typeof LOCALES)[number];

export const LOCALE_NAMES: Record<Locale, string> = {
  es: "Español", de: "Deutsch", fr: "Français", it: "Italiano", pt: "Português", nl: "Nederlands",
  pl: "Polski", ru: "Русский", sv: "Svenska", da: "Dansk", no: "Norsk", fi: "Suomi", cs: "Čeština",
  ro: "Română", el: "Ελληνικά", hu: "Magyar", tr: "Türkçe", uk: "Українська", ar: "العربية", ja: "日本語",
  ko: "한국어", zh: "中文", hi: "हिन्दी",
};

export const LOCALE_LABELS: Record<Locale, { home: string; tools: string; maps: string; guides: string; about: string; search: string; switchTo: string }> = {
  es: { home:"Inicio", tools:"Herramientas", maps:"Mapas", guides:"Guías", about:"Acerca de", search:"Buscar", switchTo:"Cambiar idioma" },
  de: { home:"Startseite", tools:"Werkzeuge", maps:"Karten", guides:"Ratgeber", about:"Über uns", search:"Suchen", switchTo:"Sprache ändern" },
  fr: { home:"Accueil", tools:"Outils", maps:"Cartes", guides:"Guides", about:"À propos", search:"Rechercher", switchTo:"Changer de langue" },
  it: { home:"Home", tools:"Strumenti", maps:"Mappe", guides:"Guide", about:"Chi siamo", search:"Cerca", switchTo:"Cambia lingua" },
  pt: { home:"Início", tools:"Ferramentas", maps:"Mapas", guides:"Guias", about:"Sobre", search:"Pesquisar", switchTo:"Mudar idioma" },
  nl: { home:"Home", tools:"Tools", maps:"Kaarten", guides:"Gidsen", about:"Over ons", search:"Zoeken", switchTo:"Taal wijzigen" },
  pl: { home:"Strona główna", tools:"Narzędzia", maps:"Mapy", guides:"Poradniki", about:"O nas", search:"Szukaj", switchTo:"Zmień język" },
  ru: { home:"Главная", tools:"Инструменты", maps:"Карты", guides:"Руководства", about:"О нас", search:"Поиск", switchTo:"Сменить язык" },
  sv: { home:"Hem", tools:"Verktyg", maps:"Kartor", guides:"Guider", about:"Om oss", search:"Sök", switchTo:"Byt språk" },
  da: { home:"Forside", tools:"Værktøjer", maps:"Kort", guides:"Guides", about:"Om os", search:"Søg", switchTo:"Skift sprog" },
  no: { home:"Hjem", tools:"Verktøy", maps:"Kart", guides:"Guider", about:"Om oss", search:"Søk", switchTo:"Bytt språk" },
  fi: { home:"Etusivu", tools:"Työkalut", maps:"Kartat", guides:"Oppaat", about:"Tietoa", search:"Hae", switchTo:"Vaihda kieltä" },
  cs: { home:"Domů", tools:"Nástroje", maps:"Mapy", guides:"Průvodci", about:"O nás", search:"Hledat", switchTo:"Změnit jazyk" },
  ro: { home:"Acasă", tools:"Instrumente", maps:"Hărți", guides:"Ghiduri", about:"Despre", search:"Caută", switchTo:"Schimbă limba" },
  el: { home:"Αρχική", tools:"Εργαλεία", maps:"Χάρτες", guides:"Οδηγοί", about:"Σχετικά", search:"Αναζήτηση", switchTo:"Αλλαγή γλώσσας" },
  hu: { home:"Kezdőlap", tools:"Eszközök", maps:"Térképek", guides:"Útmutatók", about:"Rólunk", search:"Keresés", switchTo:"Nyelv váltása" },
  tr: { home:"Ana sayfa", tools:"Araçlar", maps:"Haritalar", guides:"Rehberler", about:"Hakkımızda", search:"Ara", switchTo:"Dili değiştir" },
  uk: { home:"Головна", tools:"Інструменти", maps:"Карти", guides:"Посібники", about:"Про нас", search:"Пошук", switchTo:"Змінити мову" },
  ar: { home:"الرئيسية", tools:"الأدوات", maps:"الخرائط", guides:"الأدلة", about:"من نحن", search:"بحث", switchTo:"تغيير اللغة" },
  ja: { home:"ホーム", tools:"ツール", maps:"地図", guides:"ガイド", about:"概要", search:"検索", switchTo:"言語を変更" },
  ko: { home:"홈", tools:"도구", maps:"지도", guides:"가이드", about:"소개", search:"검색", switchTo:"언어 변경" },
  zh: { home:"首页", tools:"工具", maps:"地图", guides:"指南", about:"关于", search:"搜索", switchTo:"切换语言" },
  hi: { home:"होम", tools:"टूल्स", maps:"मैप्स", guides:"गाइड", about:"हमारे बारे में", search:"खोजें", switchTo:"भाषा बदलें" },
};

export function isLocale(value: string): value is Locale {
  return (LOCALES as readonly string[]).includes(value);
}

export function localizedPath(locale: Locale, pathname: string) {
  const clean = pathname.startsWith("/") ? pathname : `/${pathname}`;
  return `/${locale}${clean === "/" ? "" : clean}`;
}

export function localeFromPath(pathname: string): Locale | null {
  const first = pathname.split("/").filter(Boolean)[0];
  return first && isLocale(first) ? first : null;
}


export interface LocaleUI {
  free:string; copyLink:string; reset:string; advertisement:string; quickAnswer:string; howTo:string;
  methodology:string; faq:string; relatedTools:string; dataPrivacy:string; category:string; shareTool:string;
  browseAll:string; internationalSupport:string; exploreTools:string; mapTools:string; browseDirectory:string;
  browserLanguage:string; english:string; useLocation:string;
}

export const LOCALE_UI: Record<Locale, LocaleUI> = {
  es:{free:"Gratis",copyLink:"Copiar enlace",reset:"Restablecer",advertisement:"Publicidad",quickAnswer:"Respuesta rápida",howTo:"Cómo usar",methodology:"Metodología y precisión",faq:"Preguntas frecuentes",relatedTools:"Herramientas relacionadas",dataPrivacy:"Datos y privacidad",category:"Categoría",shareTool:"Compartir esta herramienta",browseAll:"Ver todas las herramientas de",internationalSupport:"Compatibilidad con idiomas internacionales",exploreTools:"Explorar herramientas",mapTools:"Herramientas de mapas",browseDirectory:"Explora el directorio completo de MapBench. Los cálculos interactivos se ejecutan en tu navegador y los resultados se pueden compartir mediante una URL.",browserLanguage:"El idioma de tu navegador es",english:"Inglés",useLocation:"Usar mi ubicación"},
  de:{free:"Kostenlos",copyLink:"Link kopieren",reset:"Zurücksetzen",advertisement:"Werbung",quickAnswer:"Kurzantwort",howTo:"Anleitung",methodology:"Methodik & Genauigkeit",faq:"Häufig gestellte Fragen",relatedTools:"Ähnliche Tools",dataPrivacy:"Daten & Datenschutz",category:"Kategorie",shareTool:"Tool teilen",browseAll:"Alle Tools anzeigen:",internationalSupport:"Internationale Sprachunterstützung",exploreTools:"Tools entdecken",mapTools:"Kartentools",browseDirectory:"Durchsuche das vollständige MapBench-Verzeichnis. Interaktive Berechnungen laufen im Browser und Ergebnisse können per URL geteilt werden.",browserLanguage:"Deine Browsersprache ist",english:"Englisch",useLocation:"Meinen Standort verwenden"},
  fr:{free:"Gratuit",copyLink:"Copier le lien",reset:"Réinitialiser",advertisement:"Publicité",quickAnswer:"Réponse rapide",howTo:"Comment utiliser",methodology:"Méthode et précision",faq:"Questions fréquentes",relatedTools:"Outils associés",dataPrivacy:"Données et confidentialité",category:"Catégorie",shareTool:"Partager cet outil",browseAll:"Voir tous les outils :",internationalSupport:"Prise en charge des langues internationales",exploreTools:"Explorer les outils",mapTools:"Outils cartographiques",browseDirectory:"Parcourez tout le répertoire MapBench. Les calculs interactifs s’exécutent dans votre navigateur et les résultats peuvent être partagés par URL.",browserLanguage:"La langue de votre navigateur est",english:"Anglais",useLocation:"Utiliser ma position"},
  it:{free:"Gratis",copyLink:"Copia link",reset:"Reimposta",advertisement:"Pubblicità",quickAnswer:"Risposta rapida",howTo:"Come usare",methodology:"Metodo e precisione",faq:"Domande frequenti",relatedTools:"Strumenti correlati",dataPrivacy:"Dati e privacy",category:"Categoria",shareTool:"Condividi questo strumento",browseAll:"Vedi tutti gli strumenti:",internationalSupport:"Supporto internazionale alle lingue",exploreTools:"Esplora gli strumenti",mapTools:"Strumenti cartografici",browseDirectory:"Sfoglia l'intera directory MapBench. I calcoli interattivi vengono eseguiti nel browser e i risultati possono essere condivisi tramite URL.",browserLanguage:"La lingua del browser è",english:"Inglese",useLocation:"Usa la mia posizione"},
  pt:{free:"Grátis",copyLink:"Copiar link",reset:"Redefinir",advertisement:"Publicidade",quickAnswer:"Resposta rápida",howTo:"Como usar",methodology:"Metodologia e precisão",faq:"Perguntas frequentes",relatedTools:"Ferramentas relacionadas",dataPrivacy:"Dados e privacidade",category:"Categoria",shareTool:"Partilhar esta ferramenta",browseAll:"Ver todas as ferramentas:",internationalSupport:"Suporte internacional de idiomas",exploreTools:"Explorar ferramentas",mapTools:"Ferramentas de mapas",browseDirectory:"Explore o diretório completo do MapBench. Os cálculos interativos são executados no navegador e os resultados podem ser partilhados por URL.",browserLanguage:"O idioma do seu navegador é",english:"Inglês",useLocation:"Usar a minha localização"},
  nl:{free:"Gratis",copyLink:"Link kopiëren",reset:"Resetten",advertisement:"Advertentie",quickAnswer:"Kort antwoord",howTo:"Zo gebruikt u het",methodology:"Methode en nauwkeurigheid",faq:"Veelgestelde vragen",relatedTools:"Gerelateerde tools",dataPrivacy:"Gegevens en privacy",category:"Categorie",shareTool:"Deze tool delen",browseAll:"Alle tools bekijken:",internationalSupport:"Internationale taalondersteuning",exploreTools:"Tools bekijken",mapTools:"Kaarttools",browseDirectory:"Bekijk de volledige MapBench-toolmap. Interactieve berekeningen worden in je browser uitgevoerd en resultaten kunnen via URL worden gedeeld.",browserLanguage:"De browsertaal is",english:"Engels",useLocation:"Mijn locatie gebruiken"},
  pl:{free:"Bezpłatne",copyLink:"Kopiuj link",reset:"Resetuj",advertisement:"Reklama",quickAnswer:"Szybka odpowiedź",howTo:"Jak używać",methodology:"Metoda i dokładność",faq:"Najczęściej zadawane pytania",relatedTools:"Powiązane narzędzia",dataPrivacy:"Dane i prywatność",category:"Kategoria",shareTool:"Udostępnij to narzędzie",browseAll:"Zobacz wszystkie narzędzia:",internationalSupport:"Międzynarodowa obsługa języków",exploreTools:"Odkryj narzędzia",mapTools:"Narzędzia mapowe",browseDirectory:"Przeglądaj cały katalog MapBench. Obliczenia interaktywne działają w przeglądarce, a wyniki można udostępniać przez URL.",browserLanguage:"Język przeglądarki to",english:"Angielski",useLocation:"Użyj mojej lokalizacji"},
  ru:{free:"Бесплатно",copyLink:"Копировать ссылку",reset:"Сбросить",advertisement:"Реклама",quickAnswer:"Краткий ответ",howTo:"Как использовать",methodology:"Методика и точность",faq:"Часто задаваемые вопросы",relatedTools:"Связанные инструменты",dataPrivacy:"Данные и конфиденциальность",category:"Категория",shareTool:"Поделиться инструментом",browseAll:"Все инструменты:",internationalSupport:"Международная поддержка языков",exploreTools:"Открыть инструменты",mapTools:"Картографические инструменты",browseDirectory:"Просматривайте весь каталог MapBench. Интерактивные расчёты выполняются в браузере, а результатами можно делиться через URL.",browserLanguage:"Язык браузера",english:"Английский",useLocation:"Использовать моё местоположение"},
  sv:{free:"Gratis",copyLink:"Kopiera länk",reset:"Återställ",advertisement:"Annons",quickAnswer:"Snabbt svar",howTo:"Så använder du verktyget",methodology:"Metod och noggrannhet",faq:"Vanliga frågor",relatedTools:"Relaterade verktyg",dataPrivacy:"Data och integritet",category:"Kategori",shareTool:"Dela verktyget",browseAll:"Visa alla verktyg:",internationalSupport:"Internationellt språkstöd",exploreTools:"Utforska verktyg",mapTools:"Kartverktyg",browseDirectory:"Bläddra i hela MapBench-katalogen. Interaktiva beräkningar körs i webbläsaren och resultat kan delas via URL.",browserLanguage:"Ditt webbläsarspråk är",english:"Engelska",useLocation:"Använd min plats"},
  da:{free:"Gratis",copyLink:"Kopiér link",reset:"Nulstil",advertisement:"Annonce",quickAnswer:"Hurtigt svar",howTo:"Sådan bruger du værktøjet",methodology:"Metode og nøjagtighed",faq:"Ofte stillede spørgsmål",relatedTools:"Relaterede værktøjer",dataPrivacy:"Data og privatliv",category:"Kategori",shareTool:"Del værktøjet",browseAll:"Se alle værktøjer:",internationalSupport:"International sprogunderstøttelse",exploreTools:"Udforsk værktøjer",mapTools:"Kortværktøjer",browseDirectory:"Gennemse hele MapBench-kataloget. Interaktive beregninger kører i browseren, og resultater kan deles via URL.",browserLanguage:"Dit browsersprog er",english:"Engelsk",useLocation:"Brug min placering"},
  no:{free:"Gratis",copyLink:"Kopier lenke",reset:"Tilbakestill",advertisement:"Annonse",quickAnswer:"Kort svar",howTo:"Slik bruker du",methodology:"Metode og nøyaktighet",faq:"Vanlige spørsmål",relatedTools:"Relaterte verktøy",dataPrivacy:"Data og personvern",category:"Kategori",shareTool:"Del verktøyet",browseAll:"Se alle verktøy:",internationalSupport:"Internasjonal språkstøtte",exploreTools:"Utforsk verktøy",mapTools:"Kartverktøy",browseDirectory:"Se hele MapBench-katalogen. Interaktive beregninger kjøres i nettleseren, og resultater kan deles via URL.",browserLanguage:"Nettleserspråket ditt er",english:"Engelsk",useLocation:"Bruk min posisjon"},
  fi:{free:"Ilmainen",copyLink:"Kopioi linkki",reset:"Nollaa",advertisement:"Mainos",quickAnswer:"Pikavastaus",howTo:"Käyttöohje",methodology:"Menetelmä ja tarkkuus",faq:"Usein kysytyt kysymykset",relatedTools:"Aiheeseen liittyvät työkalut",dataPrivacy:"Tiedot ja yksityisyys",category:"Luokka",shareTool:"Jaa tämä työkalu",browseAll:"Näytä kaikki työkalut:",internationalSupport:"Kansainvälinen kielituki",exploreTools:"Tutustu työkaluihin",mapTools:"Karttatyökalut",browseDirectory:"Selaa koko MapBench-hakemistoa. Interaktiiviset laskelmat tehdään selaimessa ja tulokset voi jakaa URL-osoitteella.",browserLanguage:"Selaimesi kieli on",english:"Englanti",useLocation:"Käytä sijaintiani"},
  cs:{free:"Zdarma",copyLink:"Kopírovat odkaz",reset:"Obnovit",advertisement:"Reklama",quickAnswer:"Rychlá odpověď",howTo:"Jak nástroj používat",methodology:"Metodika a přesnost",faq:"Časté dotazy",relatedTools:"Související nástroje",dataPrivacy:"Data a soukromí",category:"Kategorie",shareTool:"Sdílet tento nástroj",browseAll:"Zobrazit všechny nástroje:",internationalSupport:"Mezinárodní jazyková podpora",exploreTools:"Prozkoumat nástroje",mapTools:"Mapové nástroje",browseDirectory:"Procházejte celý katalog MapBench. Interaktivní výpočty probíhají v prohlížeči a výsledky lze sdílet pomocí URL.",browserLanguage:"Jazyk prohlížeče je",english:"Angličtina",useLocation:"Použít moji polohu"},
  ro:{free:"Gratuit",copyLink:"Copiază linkul",reset:"Resetează",advertisement:"Publicitate",quickAnswer:"Răspuns rapid",howTo:"Cum se folosește",methodology:"Metodă și precizie",faq:"Întrebări frecvente",relatedTools:"Instrumente asociate",dataPrivacy:"Date și confidențialitate",category:"Categorie",shareTool:"Distribuie acest instrument",browseAll:"Vezi toate instrumentele:",internationalSupport:"Suport internațional pentru limbi",exploreTools:"Explorează instrumentele",mapTools:"Instrumente pentru hărți",browseDirectory:"Răsfoiește întregul director MapBench. Calculele interactive rulează în browser, iar rezultatele pot fi partajate prin URL.",browserLanguage:"Limba browserului este",english:"Engleză",useLocation:"Folosește locația mea"},
  el:{free:"Δωρεάν",copyLink:"Αντιγραφή συνδέσμου",reset:"Επαναφορά",advertisement:"Διαφήμιση",quickAnswer:"Γρήγορη απάντηση",howTo:"Τρόπος χρήσης",methodology:"Μεθοδολογία και ακρίβεια",faq:"Συχνές ερωτήσεις",relatedTools:"Σχετικά εργαλεία",dataPrivacy:"Δεδομένα και απόρρητο",category:"Κατηγορία",shareTool:"Κοινοποίηση εργαλείου",browseAll:"Δείτε όλα τα εργαλεία:",internationalSupport:"Διεθνής υποστήριξη γλωσσών",exploreTools:"Εξερεύνηση εργαλείων",mapTools:"Εργαλεία χαρτών",browseDirectory:"Περιηγηθείτε στον πλήρη κατάλογο του MapBench. Οι διαδραστικοί υπολογισμοί εκτελούνται στο πρόγραμμα περιήγησης και τα αποτελέσματα κοινοποιούνται μέσω URL.",browserLanguage:"Η γλώσσα του προγράμματος περιήγησης είναι",english:"Αγγλικά",useLocation:"Χρήση της τοποθεσίας μου"},
  hu:{free:"Ingyenes",copyLink:"Hivatkozás másolása",reset:"Visszaállítás",advertisement:"Hirdetés",quickAnswer:"Gyors válasz",howTo:"Használat",methodology:"Módszer és pontosság",faq:"Gyakori kérdések",relatedTools:"Kapcsolódó eszközök",dataPrivacy:"Adatok és adatvédelem",category:"Kategória",shareTool:"Eszköz megosztása",browseAll:"Összes eszköz:",internationalSupport:"Nemzetközi nyelvi támogatás",exploreTools:"Eszközök felfedezése",mapTools:"Térképes eszközök",browseDirectory:"Böngészd a teljes MapBench-katalógust. Az interaktív számítások a böngészőben futnak, az eredmények URL-lel megoszthatók.",browserLanguage:"A böngésző nyelve",english:"Angol",useLocation:"Saját helyzet használata"},
  tr:{free:"Ücretsiz",copyLink:"Bağlantıyı kopyala",reset:"Sıfırla",advertisement:"Reklam",quickAnswer:"Kısa cevap",howTo:"Nasıl kullanılır",methodology:"Yöntem ve doğruluk",faq:"Sık sorulan sorular",relatedTools:"İlgili araçlar",dataPrivacy:"Veriler ve gizlilik",category:"Kategori",shareTool:"Bu aracı paylaş",browseAll:"Tüm araçları gör:",internationalSupport:"Uluslararası dil desteği",exploreTools:"Araçları keşfet",mapTools:"Harita araçları",browseDirectory:"MapBench araç dizininin tamamına göz atın. Etkileşimli hesaplamalar tarayıcıda çalışır ve sonuçlar URL ile paylaşılabilir.",browserLanguage:"Tarayıcı diliniz",english:"İngilizce",useLocation:"Konumumu kullan"},
  uk:{free:"Безкоштовно",copyLink:"Копіювати посилання",reset:"Скинути",advertisement:"Реклама",quickAnswer:"Коротка відповідь",howTo:"Як користуватися",methodology:"Методика й точність",faq:"Поширені запитання",relatedTools:"Пов’язані інструменти",dataPrivacy:"Дані та конфіденційність",category:"Категорія",shareTool:"Поділитися інструментом",browseAll:"Переглянути всі інструменти:",internationalSupport:"Міжнародна мовна підтримка",exploreTools:"Переглянути інструменти",mapTools:"Картографічні інструменти",browseDirectory:"Переглядайте весь каталог MapBench. Інтерактивні обчислення виконуються у браузері, а результатами можна ділитися через URL.",browserLanguage:"Мова вашого браузера",english:"Англійська",useLocation:"Використати моє місцезнаходження"},
  ar:{free:"مجاني",copyLink:"نسخ الرابط",reset:"إعادة ضبط",advertisement:"إعلان",quickAnswer:"إجابة سريعة",howTo:"طريقة الاستخدام",methodology:"المنهجية والدقة",faq:"الأسئلة الشائعة",relatedTools:"أدوات ذات صلة",dataPrivacy:"البيانات والخصوصية",category:"الفئة",shareTool:"مشاركة الأداة",browseAll:"عرض جميع الأدوات:",internationalSupport:"دعم اللغات الدولية",exploreTools:"استكشف الأدوات",mapTools:"أدوات الخرائط",browseDirectory:"تصفح دليل MapBench الكامل. تُجرى الحسابات التفاعلية في المتصفح ويمكن مشاركة النتائج عبر الرابط.",browserLanguage:"لغة المتصفح لديك هي",english:"الإنجليزية",useLocation:"استخدام موقعي"},
  ja:{free:"無料",copyLink:"リンクをコピー",reset:"リセット",advertisement:"広告",quickAnswer:"クイック回答",howTo:"使い方",methodology:"方法と精度",faq:"よくある質問",relatedTools:"関連ツール",dataPrivacy:"データとプライバシー",category:"カテゴリ",shareTool:"このツールを共有",browseAll:"すべてのツールを見る:",internationalSupport:"国際言語対応",exploreTools:"ツールを見る",mapTools:"地図ツール",browseDirectory:"MapBenchのツール一覧をご覧ください。インタラクティブな計算はブラウザで実行され、結果はURLで共有できます。",browserLanguage:"ブラウザの言語",english:"英語",useLocation:"現在地を使用"},
  ko:{free:"무료",copyLink:"링크 복사",reset:"초기화",advertisement:"광고",quickAnswer:"빠른 답변",howTo:"사용 방법",methodology:"방법 및 정확도",faq:"자주 묻는 질문",relatedTools:"관련 도구",dataPrivacy:"데이터 및 개인정보 보호",category:"카테고리",shareTool:"이 도구 공유",browseAll:"모든 도구 보기:",internationalSupport:"국제 언어 지원",exploreTools:"도구 탐색",mapTools:"지도 도구",browseDirectory:"MapBench 전체 도구 디렉터리를 둘러보세요. 대화형 계산은 브라우저에서 실행되며 결과를 URL로 공유할 수 있습니다.",browserLanguage:"브라우저 언어는",english:"영어",useLocation:"내 위치 사용"},
  zh:{free:"免费",copyLink:"复制链接",reset:"重置",advertisement:"广告",quickAnswer:"快速答案",howTo:"使用方法",methodology:"方法与准确性",faq:"常见问题",relatedTools:"相关工具",dataPrivacy:"数据与隐私",category:"类别",shareTool:"分享此工具",browseAll:"查看所有工具：",internationalSupport:"国际语言支持",exploreTools:"探索工具",mapTools:"地图工具",browseDirectory:"浏览完整的 MapBench 工具目录。交互式计算在浏览器中运行，结果可以通过 URL 分享。",browserLanguage:"你的浏览器语言是",english:"英语",useLocation:"使用我的位置"},
  hi:{free:"मुफ़्त",copyLink:"लिंक कॉपी करें",reset:"रीसेट करें",advertisement:"विज्ञापन",quickAnswer:"त्वरित उत्तर",howTo:"कैसे उपयोग करें",methodology:"विधि और सटीकता",faq:"अक्सर पूछे जाने वाले सवाल",relatedTools:"संबंधित टूल",dataPrivacy:"डेटा और गोपनीयता",category:"श्रेणी",shareTool:"यह टूल साझा करें",browseAll:"सभी टूल देखें:",internationalSupport:"अंतरराष्ट्रीय भाषा समर्थन",exploreTools:"टूल एक्सप्लोर करें",mapTools:"मैप टूल",browseDirectory:"पूरा MapBench टूल डायरेक्टरी देखें। इंटरैक्टिव गणनाएँ आपके ब्राउज़र में चलती हैं और परिणाम URL से साझा किए जा सकते हैं।",browserLanguage:"आपके ब्राउज़र की भाषा है",english:"अंग्रेज़ी",useLocation:"मेरी लोकेशन इस्तेमाल करें"}
};

export function getLocaleUI(locale: Locale): LocaleUI { return LOCALE_UI[locale]; }


export const CATEGORY_LABELS: Record<Locale, Record<string,string>> = {
  es:{location:"Ubicación",distance:"Distancia y rumbo",routing:"Rutas y tiempo de viaje",radius:"Radio y área",coordinates:"Coordenadas",files:"Archivos de mapas",creation:"Creación de mapas",earth:"Ciencias de la Tierra",sun:"Sol y Luna",lines:"Líneas geográficas",population:"Lugares y población"},
  de:{location:"Standort",distance:"Entfernung & Richtung",routing:"Routen & Fahrzeit",radius:"Radius & Fläche",coordinates:"Koordinaten",files:"Kartendateien",creation:"Kartenerstellung",earth:"Geowissenschaften",sun:"Sonne & Mond",lines:"Geografische Linien",population:"Orte & Bevölkerung"},
  fr:{location:"Localisation",distance:"Distance et relèvement",routing:"Itinéraires et temps de trajet",radius:"Rayon et surface",coordinates:"Coordonnées",files:"Fichiers cartographiques",creation:"Création de cartes",earth:"Sciences de la Terre",sun:"Soleil et Lune",lines:"Lignes géographiques",population:"Lieux et population"},
  it:{location:"Posizione",distance:"Distanza e direzione",routing:"Percorsi e tempi di viaggio",radius:"Raggio e area",coordinates:"Coordinate",files:"File cartografici",creation:"Creazione mappe",earth:"Scienze della Terra",sun:"Sole e Luna",lines:"Linee geografiche",population:"Luoghi e popolazione"},
  pt:{location:"Localização",distance:"Distância e direção",routing:"Rotas e tempo de viagem",radius:"Raio e área",coordinates:"Coordenadas",files:"Ficheiros de mapas",creation:"Criação de mapas",earth:"Ciências da Terra",sun:"Sol e Lua",lines:"Linhas geográficas",population:"Lugares e população"},
  nl:{location:"Locatie",distance:"Afstand en richting",routing:"Routes en reistijd",radius:"Straal en oppervlakte",coordinates:"Coördinaten",files:"Kaartbestanden",creation:"Kaarten maken",earth:"Aardwetenschappen",sun:"Zon en maan",lines:"Geografische lijnen",population:"Plaatsen en bevolking"},
  pl:{location:"Lokalizacja",distance:"Odległość i kierunek",routing:"Trasy i czas podróży",radius:"Promień i powierzchnia",coordinates:"Współrzędne",files:"Pliki map",creation:"Tworzenie map",earth:"Nauki o Ziemi",sun:"Słońce i Księżyc",lines:"Linie geograficzne",population:"Miejsca i ludność"},
  ru:{location:"Местоположение",distance:"Расстояние и направление",routing:"Маршруты и время в пути",radius:"Радиус и площадь",coordinates:"Координаты",files:"Файлы карт",creation:"Создание карт",earth:"Науки о Земле",sun:"Солнце и Луна",lines:"Географические линии",population:"Места и население"},
  sv:{location:"Plats",distance:"Avstånd och riktning",routing:"Rutter och restid",radius:"Radie och area",coordinates:"Koordinater",files:"Kartfiler",creation:"Skapa kartor",earth:"Geovetenskap",sun:"Sol och måne",lines:"Geografiska linjer",population:"Platser och befolkning"},
  da:{location:"Placering",distance:"Afstand og retning",routing:"Ruter og rejsetid",radius:"Radius og areal",coordinates:"Koordinater",files:"Kortfiler",creation:"Opret kort",earth:"Jordvidenskab",sun:"Sol og måne",lines:"Geografiske linjer",population:"Steder og befolkning"},
  no:{location:"Posisjon",distance:"Avstand og retning",routing:"Ruter og reisetid",radius:"Radius og areal",coordinates:"Koordinater",files:"Kartfiler",creation:"Lag kart",earth:"Geovitenskap",sun:"Sol og måne",lines:"Geografiske linjer",population:"Steder og befolkning"},
  fi:{location:"Sijainti",distance:"Etäisyys ja suunta",routing:"Reitit ja matka-aika",radius:"Säde ja pinta-ala",coordinates:"Koordinaatit",files:"Karttatiedostot",creation:"Karttojen luonti",earth:"Geotieteet",sun:"Aurinko ja kuu",lines:"Maantieteelliset linjat",population:"Paikat ja väestö"},
  cs:{location:"Poloha",distance:"Vzdálenost a směr",routing:"Trasy a doba cesty",radius:"Poloměr a plocha",coordinates:"Souřadnice",files:"Mapové soubory",creation:"Tvorba map",earth:"Vědy o Zemi",sun:"Slunce a Měsíc",lines:"Geografické linie",population:"Místa a obyvatelstvo"},
  ro:{location:"Locație",distance:"Distanță și direcție",routing:"Rute și timp de călătorie",radius:"Rază și suprafață",coordinates:"Coordonate",files:"Fișiere de hărți",creation:"Creare hărți",earth:"Științele Pământului",sun:"Soare și Lună",lines:"Linii geografice",population:"Locuri și populație"},
  el:{location:"Τοποθεσία",distance:"Απόσταση και κατεύθυνση",routing:"Διαδρομές και χρόνος ταξιδιού",radius:"Ακτίνα και εμβαδό",coordinates:"Συντεταγμένες",files:"Αρχεία χαρτών",creation:"Δημιουργία χαρτών",earth:"Επιστήμες της Γης",sun:"Ήλιος και Σελήνη",lines:"Γεωγραφικές γραμμές",population:"Τοποθεσίες και πληθυσμός"},
  hu:{location:"Hely",distance:"Távolság és irány",routing:"Útvonalak és menetidő",radius:"Sugár és terület",coordinates:"Koordináták",files:"Térképfájlok",creation:"Térképkészítés",earth:"Földtudomány",sun:"Nap és Hold",lines:"Földrajzi vonalak",population:"Helyek és népesség"},
  tr:{location:"Konum",distance:"Mesafe ve yön",routing:"Rotalar ve seyahat süresi",radius:"Yarıçap ve alan",coordinates:"Koordinatlar",files:"Harita dosyaları",creation:"Harita oluşturma",earth:"Yer bilimleri",sun:"Güneş ve Ay",lines:"Coğrafi çizgiler",population:"Yerler ve nüfus"},
  uk:{location:"Місцезнаходження",distance:"Відстань і напрямок",routing:"Маршрути та час у дорозі",radius:"Радіус і площа",coordinates:"Координати",files:"Файли карт",creation:"Створення карт",earth:"Науки про Землю",sun:"Сонце й Місяць",lines:"Географічні лінії",population:"Місця та населення"},
  ar:{location:"الموقع",distance:"المسافة والاتجاه",routing:"المسارات ووقت السفر",radius:"نصف القطر والمساحة",coordinates:"الإحداثيات",files:"ملفات الخرائط",creation:"إنشاء الخرائط",earth:"علوم الأرض",sun:"الشمس والقمر",lines:"الخطوط الجغرافية",population:"الأماكن والسكان"},
  ja:{location:"位置",distance:"距離と方位",routing:"ルートと移動時間",radius:"半径と面積",coordinates:"座標",files:"地図ファイル",creation:"地図作成",earth:"地球科学",sun:"太陽と月",lines:"地理的な線",population:"場所と人口"},
  ko:{location:"위치",distance:"거리 및 방향",routing:"경로 및 이동 시간",radius:"반경 및 면적",coordinates:"좌표",files:"지도 파일",creation:"지도 만들기",earth:"지구과학",sun:"태양과 달",lines:"지리적 선",population:"장소 및 인구"},
  zh:{location:"位置",distance:"距离与方向",routing:"路线与行程时间",radius:"半径与面积",coordinates:"坐标",files:"地图文件",creation:"地图创建",earth:"地球科学",sun:"太阳与月亮",lines:"地理线",population:"地点与人口"},
  hi:{location:"लोकेशन",distance:"दूरी और दिशा",routing:"रूट और यात्रा समय",radius:"रेडियस और क्षेत्रफल",coordinates:"कोऑर्डिनेट्स",files:"मैप फाइलें",creation:"मैप बनाना",earth:"पृथ्वी विज्ञान",sun:"सूर्य और चंद्रमा",lines:"भौगोलिक रेखाएँ",population:"स्थान और जनसंख्या"}
};
