// Central tool registry
export type CategoryId =
  | "location" | "distance" | "radius" | "routing" | "coordinates"
  | "files" | "creation" | "earth" | "sun" | "lines" | "population" | "network";

export interface CategoryDef {
  id: CategoryId; label: string; short: string; tone: string;
}

export const CATEGORIES: CategoryDef[] = [
  { id: "location", label: "Location", short: "County, city, state, ZIP, country and addresses.", tone: "#1d6e63" },
  { id: "distance", label: "Distance & Bearing", short: "Distances, bearings and midpoints.", tone: "#b45309" },
  { id: "routing", label: "Routing & Travel Time", short: "Routes, travel times and drive-time areas.", tone: "#9d174d" },
  { id: "radius", label: "Radius & Area", short: "Radii, rings and polygon areas.", tone: "#4d7c0f" },
  { id: "coordinates", label: "Coordinates", short: "Find and convert GPS coordinates.", tone: "#0e7490" },
  { id: "files", label: "Map Files", short: "KML, GeoJSON, GPX and CSV.", tone: "#6d28d9" },
  { id: "creation", label: "Map Creation", short: "Pins and custom maps.", tone: "#c2410c" },
  { id: "earth", label: "Earth Science", short: "Elevation, horizon, antipodes.", tone: "#155e75" },
  { id: "sun", label: "Sun & Moon", short: "Sunrise, sunset and day length.", tone: "#a16207" },
  { id: "lines", label: "Geographic Lines", short: "Equator, tropics and meridians.", tone: "#334155" },
  { id: "population", label: "Places & Population", short: "Cities and ZIP codes in a radius.", tone: "#7c2d12" },
  { id: "network", label: "IP & Network", short: "IP geolocation and network details.", tone: "#475569" },
];

export interface ToolDef {
  slug: string; name: string; short: string; intro: string;
  category: CategoryId;
  scope: "Worldwide" | "US focused" | "Major cities" | "Major airports";
  component: string; props?: Record<string, unknown>;
  keywords: string[]; popular?: boolean;
  faq: [string, string][]; howTo: string[]; related: string[]; method?: string;
}

export const TOOLS: ToolDef[] = [
  {
    slug: "find-my-location",
    name: "Find My Location",
    short: "See your current position on the map with live coordinates and nearest address.",
    intro: "One click drops a pin where you are. GPS stays in your browser; only a public reverse geocoder is used for the address.",
    category: "location", scope: "Worldwide", component: "geocoder", props: { mode: "locate" },
    keywords: ["gps", "where am i", "my location"], popular: true,
    faq: [
      ["Is my location stored?", "No. Nothing is saved on our servers."],
      ["Inaccurate position?", "GPS is best outdoors; indoors may use Wi-Fi or IP."],
    ],
    howTo: ["Press Use my location.", "Allow access when asked.", "Read coordinates and address."],
    related: ["what-county-am-i-in", "what-zip-code-am-i-in", "zip-codes-within-radius", "latitude-longitude-finder"],
  },
  {
    slug: "what-county-am-i-in",
    name: "What County Am I In?",
    short: "Find which county your location or any map point belongs to.",
    intro: "Reverse-geocodes against OpenStreetMap boundaries to report the administrative county.",
    category: "location", scope: "Worldwide", component: "geocoder", props: { mode: "locate", focus: "county" },
    keywords: ["county", "county finder"], popular: true,
    faq: [
      ["Outside the US?", "Yes — equivalent units when available."],
      ["Any point?", "Yes — click the map or paste coordinates."],
    ],
    howTo: ["Use my location or click the map.", "Read the County field."],
    related: ["what-city-am-i-in", "what-state-am-i-in", "find-my-location"],
  },
  {
    slug: "what-city-am-i-in",
    name: "What City Am I In?",
    short: "Find the city or town for your position or any map point.",
    intro: "Identifies the city or town from OpenStreetMap administrative data.",
    category: "location", scope: "Worldwide", component: "geocoder", props: { mode: "locate", focus: "city" },
    keywords: ["city", "town", "municipality"],
    faq: [["Unincorporated areas?", "County is shown when no city exists."]],
    howTo: ["Use my location or click the map.", "Read the City field."],
    related: ["what-county-am-i-in", "what-zip-code-am-i-in", "find-my-location"],
  },
  {
    slug: "what-state-am-i-in",
    name: "What State Am I In?",
    short: "Find the US state or first-level region for any point.",
    intro: "Resolves any point to its state or equivalent region worldwide.",
    category: "location", scope: "Worldwide", component: "geocoder", props: { mode: "locate", focus: "state" },
    keywords: ["state", "province", "region"],
    faq: [["Outside the US?", "Yes — provinces and state-equivalents."]],
    howTo: ["Use my location or click the map.", "Read the State field."],
    related: ["what-country-am-i-in", "what-county-am-i-in"],
  },
  {
    slug: "what-country-am-i-in",
    name: "What Country Am I In?",
    short: "Resolve any point to its country with ISO code.",
    intro: "Uses OpenStreetMap boundary data to identify the country.",
    category: "location", scope: "Worldwide", component: "geocoder", props: { mode: "locate", focus: "country" },
    keywords: ["country", "iso code"],
    faq: [["Disputed areas?", "OSM reflects de facto control for most boundaries."]],
    howTo: ["Use my location or click the map.", "Read the Country field."],
    related: ["what-state-am-i-in", "find-my-location"],
  },
  {
    slug: "what-zip-code-am-i-in",
    name: "What ZIP Code Am I In?",
    short: "Find the postal code for your location. Strong US coverage.",
    intro: "Reads the postcode from OpenStreetMap address data for your point.",
    category: "location", scope: "US focused", component: "geocoder", props: { mode: "locate", focus: "postcode" },
    keywords: ["zip", "zip code", "postcode"],
    faq: [
      ["Missing ZIP?", "Some rural areas lack postcode tags in OSM."],
      ["Non-US?", "Yes where OSM has postcode data."],
    ],
    howTo: ["Use my location or click the map.", "Read the Postcode field."],
    related: ["zip-codes-within-radius", "what-city-am-i-in", "find-my-location"],
  },
  {
    slug: "zip-codes-within-radius",
    name: "ZIP Codes Within Radius",
    short: "Find every ZIP or postal code inside a radius — map, list, CSV export.",
    intro: "Set a centre and radius to list postal codes inside the circle with distance, bearing and CSV export.",
    category: "population", scope: "Worldwide", component: "zipradius",
    keywords: ["zip codes within radius", "zip codes near me", "postal codes in radius"],
    popular: true,
    faq: [
      ["Outside the US?", "Yes — OSM postcode data worldwide."],
      ["Export?", "Yes — CSV with zip, place, distance, coordinates."],
      ["Some ZIPs missing?", "Depends on OSM coverage; try a larger radius."],
    ],
    howTo: ["Set the centre via search or map click.", "Choose unit and radius (presets 5–50).", "Find postal codes and download CSV if needed."],
    related: ["what-zip-code-am-i-in", "map-radius", "cities-within-radius"],
    method: "Nominatim postalcode query filtered by geodesic distance.",
  },
  {
    slug: "map-radius",
    name: "Map Radius Tool",
    short: "Draw a geodesic radius circle — presets, area, perimeter, export.",
    intro: "True geodesic circles with unit toggle, presets, stats and GeoJSON/KML/GPX export.",
    category: "radius", scope: "Worldwide", component: "radius",
    keywords: ["radius map", "draw circle on map", "coverage circle"],
    popular: true,
    faq: [
      ["Accurate at high latitudes?", "Yes — WGS84 geodesic."],
      ["Multiple circles?", "Yes on multi-radius mode."],
    ],
    howTo: ["Set the centre.", "Pick a preset or type a radius.", "Read stats and export if needed."],
    related: ["zip-codes-within-radius", "drive-time-map", "map-area-calculator"],
  },
  {
    slug: "drive-time-map",
    name: "Drive Time Map",
    short: "How far you can drive, bike or walk in set minutes — real isochrones.",
    intro: "Reachable areas along real roads via Valhalla — Drive, Bike, Walk, multi time contours.",
    category: "routing", scope: "Worldwide", component: "drivetime",
    keywords: ["drive time map", "isochrone", "travel time map"],
    popular: true,
    faq: [
      ["Live traffic?", "No — free-flow estimates."],
      ["Modes?", "Drive, bike, walk."],
    ],
    howTo: ["Set start point.", "Choose mode and times.", "Generate reachable area."],
    related: ["map-radius", "driving-distance-calculator"],
  },
  {
    slug: "distance-between-two-places",
    name: "Distance Between Two Places",
    short: "Great-circle distance, bearing and midpoint between any two places.",
    intro: "Straight-line distance with initial bearing and unit conversion.",
    category: "distance", scope: "Worldwide", component: "distance",
    keywords: ["distance between two places", "how far"],
    popular: true,
    faq: [["Driving distance?", "No — straight-line. Use driving distance for roads."]],
    howTo: ["Set From and To.", "Read distance and bearing."],
    related: ["bearing-calculator", "crow-flies-distance"],
  },
  {
    slug: "map-area-calculator",
    name: "Map Area Calculator",
    short: "Draw a polygon and get area in m2, km2, acres, hectares.",
    intro: "Click vertices, close the shape, read geodesic area and perimeter.",
    category: "radius", scope: "Worldwide", component: "area",
    keywords: ["area calculator", "measure area on map"],
    popular: true,
    faq: [["Curvature?", "Yes — geodesic area on the ellipsoid."]],
    howTo: ["Click to add vertices.", "Close the shape.", "Read the area table."],
    related: ["map-radius"],
  },
  {
    slug: "latitude-longitude-finder",
    name: "Latitude and Longitude Finder",
    short: "Coordinates of any place — decimal, DMS, UTM, MGRS, Plus Code.",
    intro: "Search, click or drag. All formats update live with one-click copy.",
    category: "coordinates", scope: "Worldwide", component: "latlong",
    keywords: ["latitude longitude", "gps coordinates"],
    popular: true,
    faq: [["Datum?", "WGS84 — same as GPS."]],
    howTo: ["Search or click the map.", "Copy the format you need."],
    related: ["reverse-geocoder", "find-my-location"],
  },
  {
    slug: "cities-within-radius",
    name: "Cities Within Radius",
    short: "Major world cities within a radius, sorted by distance — CSV export.",
    intro: "Lists curated major cities inside your radius with distance, bearing and population.",
    category: "population", scope: "Major cities", component: "cities", props: { mode: "cities" },
    keywords: ["cities in radius", "cities near me"],
    faq: [["Which cities?", "200+ major cities and capitals."]],
    howTo: ["Set centre and radius.", "Read the list.", "Export CSV."],
    related: ["zip-codes-within-radius", "population-within-radius", "map-radius"],
  },
  {
    slug: "population-within-radius",
    name: "Population Within Radius",
    short: "Estimate population in a radius from major-city data.",
    intro: "Sums major-city populations inside the radius and shows contributors.",
    category: "population", scope: "Major cities", component: "cities", props: { mode: "population" },
    keywords: ["population in radius", "catchment population"],
    faq: [["Census count?", "No — labelled estimate from major cities only."]],
    howTo: ["Set centre and radius.", "Read total and cities."],
    related: ["cities-within-radius", "zip-codes-within-radius"],
  },
  {
    slug: "elevation-finder",
    name: "Elevation Finder",
    short: "Elevation above sea level for any point on Earth.",
    intro: "Click or search to read elevation from open terrain data.",
    category: "earth", scope: "Worldwide", component: "elevation",
    keywords: ["elevation", "altitude"],
    faq: [["Accuracy?", "Planning-grade DEM, not survey-grade."]],
    howTo: ["Search or click.", "Read elevation in m and ft."],
    related: ["find-my-location", "latitude-longitude-finder"],
  },
  {
    slug: "bearing-calculator",
    name: "Bearing Calculator",
    short: "Compass bearing between two points — initial, final, cardinal.",
    intro: "Great-circle initial and reverse bearings between two points.",
    category: "distance", scope: "Worldwide", component: "bearing",
    keywords: ["bearing", "compass direction"],
    faq: [["True or magnetic?", "True north from the great-circle path."]],
    howTo: ["Set start and end.", "Read bearing and distance."],
    related: ["distance-between-two-places"],
  },
  {
    slug: "reverse-geocoder",
    name: "Reverse Geocoder",
    short: "Turn coordinates into a structured address.",
    intro: "Paste coordinates or click the map for road, city, region, postcode, country.",
    category: "location", scope: "Worldwide", component: "geocoder", props: { mode: "reverse" },
    keywords: ["reverse geocoding", "coordinates to address"],
    popular: true,
    faq: [["Service?", "OpenStreetMap Nominatim."]],
    howTo: ["Enter coordinates or click map.", "Copy fields."],
    related: ["latitude-longitude-finder", "find-my-location"],
  },
  {
    slug: "ip-address-lookup",
    name: "IP Address Lookup",
    short: "Approximate location, ISP and network details for a public IP.",
    intro: "Enter an IP or detect yours for network geolocation details.",
    category: "network", scope: "Worldwide", component: "iplookup",
    keywords: ["ip lookup", "ip geolocation"],
    faq: [["Exact location?", "No — network exit, not street address."]],
    howTo: ["Enter IP or detect yours.", "Read city, region, country, org."],
    related: ["find-my-location"],
  },
  {
    slug: "address-to-coordinates",
    name: "Address to Coordinates",
    short: "Geocode any address to latitude and longitude.",
    intro: "Type a full or partial address and get WGS84 coordinates plus a map pin.",
    category: "location", scope: "Worldwide", component: "geocoder", props: { mode: "forward" },
    keywords: ["geocode", "address to lat long", "forward geocoding"],
    popular: true,
    faq: [
      ["How accurate?", "Usually building-level in cities; coarser in rural areas."],
      ["Which data?", "OpenStreetMap Nominatim."],
    ],
    howTo: ["Enter an address.", "Press look up.", "Copy coordinates or open on the map."],
    related: ["coordinates-to-address", "reverse-geocoder", "latitude-longitude-finder"],
  },
  {
    slug: "coordinates-to-address",
    name: "Coordinates to Address",
    short: "Convert lat/long into a readable address.",
    intro: "Paste coordinates to reverse-geocode into a structured address.",
    category: "location", scope: "Worldwide", component: "geocoder", props: { mode: "reverse" },
    keywords: ["coordinates to address", "reverse geocode"],
    faq: [["Same as reverse geocoder?", "Yes — focused entry point for coordinate paste workflows."]],
    howTo: ["Paste latitude and longitude.", "Read the address fields."],
    related: ["address-to-coordinates", "reverse-geocoder"],
  },
  {
    slug: "driving-distance-calculator",
    name: "Driving Distance Calculator",
    short: "Road distance and drive time between two places.",
    intro: "Calculates driving distance and duration along real roads using open routing data.",
    category: "routing", scope: "Worldwide", component: "route",
    keywords: ["driving distance", "road distance", "drive time"],
    popular: true,
    faq: [
      ["Live traffic?", "No — typical free-flow speeds."],
      ["Worldwide?", "Yes where OpenStreetMap roads exist."],
    ],
    howTo: ["Set origin and destination.", "Read distance and duration."],
    related: ["drive-time-map", "distance-between-two-places", "multi-stop-route-planner"],
  },
  {
    slug: "multi-stop-route-planner",
    name: "Multi-Stop Route Planner",
    short: "Plan a route with multiple stops and see total distance and time.",
    intro: "Add several stops, order them, and get a full road route with leg breakdown.",
    category: "routing", scope: "Worldwide", component: "route",
    keywords: ["multi stop route", "route planner", "waypoints"],
    faq: [["Optimize order?", "Use the route optimizer tool for best-order suggestions."]],
    howTo: ["Add stops on the map or by search.", "Calculate the route.", "Review total distance and time."],
    related: ["driving-distance-calculator", "drive-time-map"],
  },
  {
    slug: "kml-viewer",
    name: "KML Viewer",
    short: "Open and view KML or KMZ files on an interactive map.",
    intro: "Drop a KML/KMZ file to plot placemarks, paths and polygons in the browser — nothing is uploaded to our servers.",
    category: "files", scope: "Worldwide", component: "fileviewer", props: { format: "kml" },
    keywords: ["kml viewer", "kmz viewer", "open kml"],
    faq: [
      ["Is my file uploaded?", "No — parsing happens in your browser."],
      ["KMZ supported?", "Yes — zipped KML is unpacked locally."],
    ],
    howTo: ["Choose a KML or KMZ file.", "Inspect features on the map."],
    related: ["gpx-viewer", "csv-to-map"],
  },
  {
    slug: "gpx-viewer",
    name: "GPX Viewer",
    short: "View GPX tracks and waypoints on a map.",
    intro: "Load a GPX file to see tracks, routes and waypoints without uploading the file.",
    category: "files", scope: "Worldwide", component: "fileviewer", props: { format: "gpx" },
    keywords: ["gpx viewer", "gps track", "open gpx"],
    faq: [["Uploaded?", "No — processed entirely in the browser."]],
    howTo: ["Open a GPX file.", "Explore the track on the map."],
    related: ["kml-viewer"],
  },
  {
    slug: "csv-to-map",
    name: "CSV to Map",
    short: "Plot a CSV of coordinates or addresses on a map.",
    intro: "Upload or paste CSV with lat/long columns to drop pins and export the map data.",
    category: "files", scope: "Worldwide", component: "csv",
    keywords: ["csv to map", "plot csv", "spreadsheet map"],
    faq: [["Required columns?", "Latitude and longitude, or a single address column for geocoding."]],
    howTo: ["Paste or upload CSV.", "Map the columns.", "View pins and export."],
    related: ["kml-viewer", "address-to-coordinates"],
  },
  {
    slug: "sunrise-sunset-calculator",
    name: "Sunrise Sunset Calculator",
    short: "Sunrise, sunset and solar noon for any place and date.",
    intro: "Pick a location and date to get sunrise, sunset, dawn, dusk and day length.",
    category: "sun", scope: "Worldwide", component: "sun",
    keywords: ["sunrise", "sunset", "day length"],
    faq: [["Time zone?", "Results use the location local timezone when known."]],
    howTo: ["Set location and date.", "Read sunrise, sunset and day length."],
    related: ["find-my-location", "what-timezone-am-i-in"],
  },
  {
    slug: "what-timezone-am-i-in",
    name: "What Timezone Am I In?",
    short: "IANA timezone, UTC offset and local time for any place.",
    intro: "Resolves a point to its timezone and shows current local time and offset.",
    category: "location", scope: "Worldwide", component: "tztool",
    keywords: ["timezone", "what timezone", "utc offset"],
    faq: [["How is timezone decided?", "From timezone boundary data for the coordinates."]],
    howTo: ["Use my location or search a place.", "Read timezone and local time."],
    related: ["find-my-location", "sunrise-sunset-calculator"],
  },
];

export const toolBySlug = new Map(TOOLS.map((t) => [t.slug, t]));
export const popularTools = TOOLS.filter((t) => t.popular);
export const toolsByCategory = (id: CategoryId) => TOOLS.filter((t) => t.category === id);
export const STATIC_LINKS = [
  { href: "/", name: "Home", keywords: ["home"] },
  { href: "/tools", name: "All Tools", keywords: ["directory"] },
  { href: "/about", name: "About", keywords: ["about"] },
  { href: "/methodology", name: "Methodology", keywords: ["methodology"] },
  { href: "/data-sources", name: "Data Sources", keywords: ["data"] },
  { href: "/privacy", name: "Privacy", keywords: ["privacy"] },
  { href: "/contact", name: "Contact", keywords: ["contact"] },
];
