"use client";
import { useEffect, useState } from "react";
import { readUrlParams, syncUrl, CopyBtn, ErrorBox, Spinner, Stat, Field } from "@/components/ui";

type IpData={ip:string;success?:boolean;type?:string;continent?:string;country?:string;country_code?:string;region?:string;city?:string;postal?:string;latitude?:number;longitude?:number;timezone?:{id?:string;abbr?:string;utc?:string};connection?:{isp?:string;org?:string;asn?:number;domain?:string};flag?:{emoji?:string}};
export default function IpLookupTool({params}:{params?:Record<string,unknown>}){
 const [query,setQuery]=useState(()=>readUrlParams().get("ip")??""); const [data,setData]=useState<IpData|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
 const lookup=async(ip?:string)=>{setBusy(true);setError(null);try{const q=(ip??query).trim();const url=q?"https://ipwho.is/"+encodeURIComponent(q):"https://ipwho.is/";const res=await fetch(url);const d=await res.json();if(!res.ok||d.success===false)throw new Error(d.message||"IP lookup failed.");setData(d);if(d.ip)syncUrl({ip:d.ip});}catch(e:any){setError(e?.message??"IP lookup failed.");setData(null)}finally{setBusy(false)}};
 useEffect(()=>{if(params?.auto===true)lookup()},[]);
 const rows=data?[["IP address",data.ip],["Type",data.type],["Country",(data.flag?.emoji??"")+" "+(data.country??"")+" ("+(data.country_code??"")+")"],["Region",data.region],["City",data.city],["Postal code",data.postal],["ISP",data.connection?.isp],["Organization",data.connection?.org],["ASN",data.connection?.asn?"AS"+data.connection.asn:""],["Domain",data.connection?.domain],["Timezone",data.timezone?.id],["Coordinates",data.latitude!=null&&data.longitude!=null?data.latitude+", "+data.longitude:""]].filter(([,v])=>v):[];
 return <div className="grid gap-4 lg:grid-cols-[360px,1fr]"><div className="card space-y-4 p-4"><Field label="IP address"><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="8.8.8.8" onKeyDown={e=>{if(e.key==="Enter")lookup()}} /></Field><button className="btn btn-primary w-full" type="button" onClick={()=>lookup()} disabled={busy}>{busy?<Spinner label="Looking up…" />:"Look up IP address"}</button><button className="btn btn-ghost w-full" type="button" onClick={()=>{setQuery("");lookup("")}} disabled={busy}>Detect my public IP</button>{error&&<ErrorBox>{error}</ErrorBox>}{data&&<div className="grid grid-cols-2 gap-2"><Stat label="Country" value={(data.flag?.emoji??"")+" "+(data.country??"—")} /><Stat label="Timezone" value={data.timezone?.id??"—"} /><Stat label="ISP" value={data.connection?.isp??"—"} /><Stat label="ASN" value={data.connection?.asn?"AS"+data.connection.asn:"—"} /></div>}</div><div className="card p-4"><div className="label">IP intelligence</div>{data?<><div className="mt-3 overflow-x-auto"><table className="tbl"><tbody>{rows.map(([k,v])=><tr key={k}><td className="w-1/3 text-mute">{k}</td><td className="font-medium">{v}<span className="float-right"><CopyBtn text={String(v)} label="" /></span></td></tr>)}</tbody></table></div>{data.latitude!=null&&data.longitude!=null&&<div className="mt-4 rounded-lg bg-brand-soft p-3 text-sm"><strong>Map position:</strong> {data.latitude}, {data.longitude}</div>}</>:<p className="mt-3 text-sm text-mute">Enter an IPv4 or IPv6 address, or detect your current public IP to see country, region, city, coordinates, timezone, ISP, organization and ASN details.</p>}</div></div>;
}
